// <auto-generated />
using System;
using CodeOrbit.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeOrbit.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeOrbit.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Language = 0,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Language = 1,
                            Name = "Java"
                        },
                        new
                        {
                            Id = 3,
                            Language = 2,
                            Name = "Kotlin"
                        },
                        new
                        {
                            Id = 4,
                            Language = 3,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 5,
                            Language = 4,
                            Name = "JavaScript"
                        });
                });

            modelBuilder.Entity("CodeOrbit.Domain.Entities.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCorrect = true,
                            OptionText = "int x = 5;",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsCorrect = false,
                            OptionText = "var x = 5;",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsCorrect = false,
                            OptionText = "let x = 5;",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 4,
                            IsCorrect = false,
                            OptionText = "x := 5;",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 5,
                            IsCorrect = true,
                            OptionText = "Veri sorgulama yöntemi",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 6,
                            IsCorrect = false,
                            OptionText = "Yeni sınıf oluşturma",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 7,
                            IsCorrect = false,
                            OptionText = "Exception handling",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 8,
                            IsCorrect = false,
                            OptionText = "GUI tasarımı",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 9,
                            IsCorrect = true,
                            OptionText = "Doğru",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 10,
                            IsCorrect = false,
                            OptionText = "Yanlış",
                            QuestionId = 3
                        },
                        new
                        {
                            Id = 11,
                            IsCorrect = true,
                            OptionText = "List",
                            QuestionId = 4
                        },
                        new
                        {
                            Id = 12,
                            IsCorrect = true,
                            OptionText = "catch veya finally bloğu gelir",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 13,
                            IsCorrect = false,
                            OptionText = "else bloğu gelir",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 14,
                            IsCorrect = false,
                            OptionText = "void bloğu gelir",
                            QuestionId = 5
                        },
                        new
                        {
                            Id = 15,
                            IsCorrect = true,
                            OptionText = "Sınıfların şablonu",
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 16,
                            IsCorrect = false,
                            OptionText = "Yalnızca değişken tutar",
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 17,
                            IsCorrect = false,
                            OptionText = "Exception türü",
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 18,
                            IsCorrect = false,
                            OptionText = "Sadece static metodlar içerir",
                            QuestionId = 6
                        },
                        new
                        {
                            Id = 19,
                            IsCorrect = true,
                            OptionText = "Tip güvenli veri yapısı",
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 20,
                            IsCorrect = false,
                            OptionText = "Exception handling yöntemi",
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 21,
                            IsCorrect = false,
                            OptionText = "GUI tasarım yöntemi",
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 22,
                            IsCorrect = false,
                            OptionText = "Sadece class",
                            QuestionId = 7
                        },
                        new
                        {
                            Id = 23,
                            IsCorrect = false,
                            OptionText = "Doğru",
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 24,
                            IsCorrect = true,
                            OptionText = "Yanlış",
                            QuestionId = 8
                        },
                        new
                        {
                            Id = 25,
                            IsCorrect = true,
                            OptionText = "final",
                            QuestionId = 9
                        },
                        new
                        {
                            Id = 26,
                            IsCorrect = true,
                            OptionText = "extends anahtar kelimesi kullanılır",
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 27,
                            IsCorrect = false,
                            OptionText = "implements anahtar kelimesi kullanılır",
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 28,
                            IsCorrect = false,
                            OptionText = "inherits anahtar kelimesi kullanılır",
                            QuestionId = 10
                        },
                        new
                        {
                            Id = 29,
                            IsCorrect = true,
                            OptionText = "val x = 5",
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 30,
                            IsCorrect = false,
                            OptionText = "int x = 5",
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 31,
                            IsCorrect = false,
                            OptionText = "let x = 5",
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 32,
                            IsCorrect = false,
                            OptionText = "var x: Int = 5",
                            QuestionId = 11
                        },
                        new
                        {
                            Id = 33,
                            IsCorrect = true,
                            OptionText = "?.",
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 34,
                            IsCorrect = false,
                            OptionText = "?",
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 35,
                            IsCorrect = false,
                            OptionText = "!!",
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 36,
                            IsCorrect = false,
                            OptionText = "null",
                            QuestionId = 12
                        },
                        new
                        {
                            Id = 37,
                            IsCorrect = true,
                            OptionText = "Doğru",
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 38,
                            IsCorrect = false,
                            OptionText = "Yanlış",
                            QuestionId = 13
                        },
                        new
                        {
                            Id = 39,
                            IsCorrect = true,
                            OptionText = "val",
                            QuestionId = 14
                        },
                        new
                        {
                            Id = 40,
                            IsCorrect = true,
                            OptionText = "list = []",
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 41,
                            IsCorrect = false,
                            OptionText = "list = {}",
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 42,
                            IsCorrect = false,
                            OptionText = "list = ()",
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 43,
                            IsCorrect = false,
                            OptionText = "list = <>",
                            QuestionId = 15
                        },
                        new
                        {
                            Id = 44,
                            IsCorrect = true,
                            OptionText = "Doğru",
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 45,
                            IsCorrect = false,
                            OptionText = "Yanlış",
                            QuestionId = 16
                        },
                        new
                        {
                            Id = 46,
                            IsCorrect = true,
                            OptionText = "def",
                            QuestionId = 17
                        },
                        new
                        {
                            Id = 47,
                            IsCorrect = true,
                            OptionText = "var, let, const",
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 48,
                            IsCorrect = false,
                            OptionText = "int, string, bool",
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 49,
                            IsCorrect = false,
                            OptionText = "val, var",
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 50,
                            IsCorrect = false,
                            OptionText = "define, set",
                            QuestionId = 18
                        },
                        new
                        {
                            Id = 51,
                            IsCorrect = false,
                            OptionText = "Doğru",
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 52,
                            IsCorrect = true,
                            OptionText = "Yanlış",
                            QuestionId = 19
                        },
                        new
                        {
                            Id = 53,
                            IsCorrect = true,
                            OptionText = "function",
                            QuestionId = 20
                        });
                });

            modelBuilder.Entity("CodeOrbit.Domain.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DifficultyLevel = 0,
                            QuestionText = "C#'ta değişken nasıl tanımlanır?",
                            QuestionType = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            DifficultyLevel = 1,
                            QuestionText = "C#'ta LINQ nedir?",
                            QuestionType = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            DifficultyLevel = 0,
                            QuestionText = "C# bir nesne yönelimli dildir.",
                            QuestionType = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            DifficultyLevel = 1,
                            QuestionText = "C#'ta bir listeyi tanımlamak için ____<int> list = new() kullanılır.",
                            QuestionType = 2
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            DifficultyLevel = 0,
                            QuestionText = "C#'ta try bloğundan sonra gelen blok...",
                            QuestionType = 3
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            DifficultyLevel = 1,
                            QuestionText = "Java'da interface nedir?",
                            QuestionType = 0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            DifficultyLevel = 2,
                            QuestionText = "Java'da generic nedir?",
                            QuestionType = 0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            DifficultyLevel = 1,
                            QuestionText = "Java'da çoklu kalıtım doğrudan desteklenir.",
                            QuestionType = 1
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            DifficultyLevel = 0,
                            QuestionText = "Java'da sabit tanımlamak için ____ anahtar kelimesi kullanılır.",
                            QuestionType = 2
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            DifficultyLevel = 0,
                            QuestionText = "Java'da bir sınıfın başka bir sınıftan türemesi için...",
                            QuestionType = 3
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            DifficultyLevel = 0,
                            QuestionText = "Kotlin'de değişken nasıl tanımlanır?",
                            QuestionType = 0
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            DifficultyLevel = 1,
                            QuestionText = "Kotlin'de null kontrolü nasıl yapılır?",
                            QuestionType = 0
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            DifficultyLevel = 0,
                            QuestionText = "Kotlin, Java ile %100 uyumludur.",
                            QuestionType = 1
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            DifficultyLevel = 0,
                            QuestionText = "Kotlin'de değiştirilemez değişken tanımlamak için ____ kullanılır.",
                            QuestionType = 2
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            DifficultyLevel = 0,
                            QuestionText = "Python'da liste nasıl tanımlanır?",
                            QuestionType = 0
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            DifficultyLevel = 0,
                            QuestionText = "Python yorumlanan bir dildir.",
                            QuestionType = 1
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            DifficultyLevel = 0,
                            QuestionText = "Python'da fonksiyon tanımlamak için ____ anahtar kelimesi kullanılır.",
                            QuestionType = 2
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 5,
                            DifficultyLevel = 0,
                            QuestionText = "JavaScript'te değişken tanımlamak için hangi anahtar kelimeler kullanılır?",
                            QuestionType = 0
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 5,
                            DifficultyLevel = 1,
                            QuestionText = "JavaScript yalnızca tarayıcıda çalışır.",
                            QuestionType = 1
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 5,
                            DifficultyLevel = 0,
                            QuestionText = "JavaScript'te bir fonksiyon tanımlamak için ____ anahtar kelimesi kullanılır.",
                            QuestionType = 2
                        });
                });

            modelBuilder.Entity("CodeOrbit.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CodeOrbit.Domain.Entities.UserProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId");

                    b.ToTable("UserProgresses");
                });

            modelBuilder.Entity("CodeOrbit.Domain.Entities.Option", b =>
                {
                    b.HasOne("CodeOrbit.Domain.Entities.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CodeOrbit.Domain.Entities.Question", b =>
                {
                    b.HasOne("CodeOrbit.Domain.Entities.Category", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CodeOrbit.Domain.Entities.UserProgress", b =>
                {
                    b.HasOne("CodeOrbit.Domain.Entities.Question", "Question")
                        .WithMany("UserProgresses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeOrbit.Domain.Entities.User", "User")
                        .WithMany("UserProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeOrbit.Domain.Entities.Category", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("CodeOrbit.Domain.Entities.Question", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("UserProgresses");
                });

            modelBuilder.Entity("CodeOrbit.Domain.Entities.User", b =>
                {
                    b.Navigation("UserProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
